version: "3"
services:
#  cloudFileStorage:
#    build: ./src
#    ports:
#      - '8080:8080'
#    volumes:
#      - ./src:/cloudFileStorage

  mysql:
    image: 'mysql:latest'
    restart: always
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_DATABASE=CloudFileStorage'
      - 'MYSQL_ROOT_PASSWORD=password'
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
#  redis:
#    image: 'redis:latest'
#    ports:
#      - '6379'
volumes:
  mysql_data:
