version: "3"
services:
  cloud-file-storage:
    build: .
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - mysql
      - minio
      - redis
    environment:
      - 'MYSQL_HOST=mysql'
      - 'MYSQL_PORT=3306'
      - 'MYSQL_DATABASE=CloudFileStorage'
      - 'MYSQL_USER=CFS_User'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'REDIS_HOST=redis'
      - 'REDIS_PORT=6379'
      - 'MINIO_HOST=minio'
      - 'MINIO_PORT=9000'
      - 'MINIO_ROOT_USER=minio'
      - 'MINIO_ROOT_PASSWORD=password'
      - 'MINIO_BUCKET_NAME=user-files'
  mysql:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_DATABASE=CloudFileStorage'
      - 'MYSQL_USER=CFS_User'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  minio:
    image: minio/minio
    command: server /data --console-address ":9090"
    restart: always
    ports:
      - '9000:9000'
      - '9001:9090'
    environment:
      - 'MINIO_ROOT_USER=minio'
      - 'MINIO_ROOT_PASSWORD=password'
      - 'MINIO_BUCKET_NAME=user-files'
    volumes:
      - minio_data:/data
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - redis_data:/data
volumes:
  mysql_data:
  minio_data:
  redis_data:
