version: "3"
services:
  cloud-file-storage:
    image: crystalised/cloud-file-storage
    ports:
      - '9091:8080'
    restart: always
    depends_on:
      - postgres
      - minio
      - redis
    environment:
      - 'POSTGRES_HOST=postgres'
      - 'POSTGRES_PORT=5432'
      - 'POSTGRES_DB=CloudFileStorage'
      - 'POSTGRES_USER=CFS_User'
      - 'POSTGRES_PASSWORD=password'
      - 'REDIS_HOST=redis'
      - 'REDIS_PORT=6379'
      - 'MINIO_HOST=minio'
      - 'MINIO_PORT=9000'
      - 'MINIO_ROOT_USER=minio'
      - 'MINIO_ROOT_PASSWORD=password'
      - 'MINIO_BUCKET_NAME=user-files'
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_DB=CloudFileStorage'
      - 'POSTGRES_USER=CFS_User'
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  minio:
    image: minio/minio
    command: server /data --console-address ":9090"
    ports:
      - '9000:9000'
      - '9001:9090'
    environment:
      - 'MINIO_ROOT_USER=minio'
      - 'MINIO_ROOT_PASSWORD=password'
      - 'MINIO_BUCKET_NAME=user-files'
    volumes:
      - minio_data:/data
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  minio_data:
  redis_data:
