CREATE TABLE IF NOT EXISTS users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(20) UNIQUE NOT NULL,
    password varchar(100) NOT NULL,
    role varchar(20) NOT NULL
);